services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    ports:
      - "9100:9100"

    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy-data:/var/lib/alloy

    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy

volumes:
  alloy-data: