discovery.docker "containers" {
  host = "unix:///var/run/docker.sock"
}

discovery.relabel "containers" {
  targets = discovery.docker.containers.targets

  rule {
    source_labels = ["__meta_docker_container_name"]
    regex         = "/(.+)"
    target_label  = "container"
  }

  rule {
    target_label = "server"
    replacement  = "srv1579547"
  }
}

loki.source.docker "containers" {
  host = "unix:///var/run/docker.sock"

  targets = discovery.relabel.containers.output

  forward_to = [loki.write.central.receiver]
}

loki.write "central" {
  endpoint {
    url = "http://72.62.115.40:3100/loki/api/v1/push"
  }
}